{{- if .Values.factoryinsight.ingress.enabled -}}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "factorycube-server.fullname" . }}-factoryinsight-ingress
  labels:
     {{- include "factorycube-server.labels.factoryinsight" . | nindent 4 }}
  {{- if .Values.factoryinsight.ingress.annotations }}
  annotations:
    {{- toYaml .Values.factoryinsight.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.factoryinsight.ingress.publicHost }}
    secretName: {{ .Values.factoryinsight.ingress.publicHostSecretName }} 
  rules:
    - host: factoryinsight
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "factorycube-server.fullname" . }}-factoryinsight-service
              servicePort: 80
    - host: {{ .Values.factoryinsight.ingress.publicHost }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "factorycube-server.fullname" . }}-factoryinsight-service
              servicePort: 80
{{- end -}}
