{{- if .Values.mqtttoblob.enabled -}}
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ include "factorycube-server.fullname" . }}-mqtttoblob
  labels:
     {{- include "factorycube-server.labels.mqtttoblob" . | nindent 4 }}
  {{- if .Values.mqtttoblob.annotations }}
  annotations:
    {{- toYaml .Values.mqtttoblob.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.mqtttoblob.replicas }} 
  selector:
    matchLabels:
      name: {{ include "factorycube-server.fullname" . }}-mqtttoblob
  strategy:  
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: {{ include "factorycube-server.fullname" . }}-mqtttoblob
        {{- include "factorycube-server.labels.mqtttoblob" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    name: {{ include "factorycube-server.fullname" . }}-mqtttoblob
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ include "factorycube-server.fullname" . }}-mqtttoblob
          {{- if .Values.mqtttoblob.image.tag }}
          image: {{ .Values.mqtttoblob.image.repository }}:{{ .Values.mqtttoblob.image.tag }}
          {{- else }}
          image: {{ .Values.mqtttoblob.image.repository }}:{{ .Chart.AppVersion }}
          {{- end }}
          imagePullPolicy: {{ .Values.mqtttoblob.image.pullPolicy }}
          env:
            - name: CERTIFICATE_NAME
              value: NO_CERT
              
            - name: LOGGING_LEVEL
              value: "DEBUG"
              
            - name: BROKER_PORT
              value: "1883"
              
            - name: BROKER_URL
              value: tcp://{{ include "factorycube-server.fullname" . }}-vernemq-local-service
              
            - name: BUCKET_NAME
              value: "umh"
              
            - name: TOPIC
              value: "ia/productImage/#"
              
            - name: IMAGE_UID
              value: "imageUID"
              
            - name: IMAGE
              value: "image"
              
            - name: IMAGE_BYTES
              value: "image_bytes"
              
            - name: MINIO_URL
              value: {{ include "factorycube-server.fullname" . }}-minio-service
              
            - name: MINIO_ACCESS_KEY
              valueFrom: 
                secretKeyRef:
                  name: umhminio-secret
                  key: accessKey   
              
            - name: MINIO_SECRET_KEY
              valueFrom: 
                secretKeyRef:
                  name: umhminio-secret
                  key: secretKey       
            
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          
          # define a liveness probe that checks every 5 seconds, starting after 5 seconds
          # livenessProbe:
          #   httpGet:
          #     path: /live
          #     port: 8086
          #   initialDelaySeconds: 30
          #   periodSeconds: 5

          # define a readiness probe that checks every 5 seconds
          #readinessProbe:
          #  httpGet:
          #    path: /ready
          #    port: 8086
          #  periodSeconds: 5
          resources: {}
      serviceAccountName: ""
      restartPolicy: Always
{{- end -}}

