---
{{if .Values._000_commonConfig.datasources.sensorconnect.enabled}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-sensorconnect
  labels:
    {{- include "united-manufacturing-hub.labels.sensorconnect" . | nindent 4}}
    app.kubernetes.io/component: "sensorconnect"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "united-manufacturing-hub.labels.sensorconnect" . | nindent 6}}
      app.kubernetes.io/component: "sensorconnect"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "united-manufacturing-hub.labels.sensorconnect" . | nindent 8}}
        app.kubernetes.io/component: "sensorconnect"
    spec:
      containers:
        - name: {{include "united-manufacturing-hub.fullname" .}}-sensorconnect
          {{if .Values.sensorconnect.tag}}
          image: {{.Values.sensorconnect.image}}:{{.Values.sensorconnect.tag}}
          {{- else}}
          image: {{.Values.sensorconnect.image}}:{{.Chart.AppVersion}}
          {{end}}
          resources:
            limits:
              cpu: {{.Values.sensorconnect.resources.limits.cpu}}
              memory: {{.Values.sensorconnect.resources.limits.memory}}
            requests:
              cpu: {{.Values.sensorconnect.resources.requests.cpu}}
              memory: {{.Values.sensorconnect.resources.requests.memory}}
          env:
            - name: PYTHONUNBUFFERED
              value: "0"
            - name: TRANSMITTERID
              value: {{.Values._000_commonConfig.serialNumber | quote}}
            - name: BROKER_URL
              value: mqtt://{{include "united-manufacturing-hub.fullname" .}}-vernemq-local-service:1883
            - name: IP_RANGE
              value: {{.Values._000_commonConfig.datasources.sensorconnect.iprange | quote}}

      serviceAccountName: {{include "united-manufacturing-hub.serviceAccountName" .}}
      restartPolicy: Always

{{end}}
