
{{- if .Values.AAAservices.mqttbridge.enabled -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "factorycube-unified.fullname" . }}-mqttbridge
  labels:
    {{- include "factorycube-unified.labels.mqttbridge" . | nindent 4 }}
spec:
  serviceName: {{ include "factorycube-unified.fullname" . }}-mqttbridge
  replicas: 1
  selector:
    matchLabels:
      {{- include "factorycube-unified.labels.mqttbridge" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "factorycube-unified.labels.mqttbridge" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "factorycube-unified.fullname" . }}-mqttbridge
        {{- if .Values.mqttbridge.tag }}
        image: {{ .Values.mqttbridge.image }}:{{ .Values.mqttbridge.tag }}
        {{- else }}
        image: {{ .Values.mqttbridge.image }}:{{ .Chart.AppVersion }}
        {{- end }}
        volumeMounts:
        - name: {{ include "factorycube-unified.fullname" . }}-mqttbridge-data
          mountPath: /data/queue
        - name: {{ include "factorycube-unified.fullname" . }}-mqttbridge-certificates
          mountPath: /SSL_certs/remote
          readOnly: true
        resources:
          limits:
            cpu: {{ .Values.mqttbridge.resources.limits.cpu }}
            memory: {{ .Values.mqttbridge.resources.limits.memory }}
          requests:
            cpu: {{ .Values.mqttbridge.resources.requests.cpu }}
            memory: {{ .Values.mqttbridge.resources.requests.memory }}
        env:
        - name: REMOTE_CERTIFICATE_NAME
          value: {{ .Values.AAAserialNumber }}
        - name: REMOTE_BROKER_URL
          value: {{ .Values.AAAmqttBridgeURL }}
        - name: REMOTE_SUB_TOPIC
          value: ia
        - name: REMOTE_PUB_TOPIC
          value: {{ .Values.AAAmqttBridgeTopic }}
        - name: REMOTE_PUB_TOPIC
          value: {{ .Values.AAAmqttBridgeTopic }}
        - name: REMOTE_BROKER_SSL_ENABLED
          value: "true" 
        - name: LOCAL_CERTIFICATE_NAME
          value: "LOCAL" 
        - name: LOCAL_BROKER_URL
          value: 'mqtt://{{ include "factorycube-unified.fullname" . }}-emqxedge-headless:1883'
        - name: LOCAL_SUB_TOPIC
          value: {{ .Values.AAAmqttBridgeTopic }}
        - name: LOCAL_PUB_TOPIC
          value: "ia" 
        - name: LOCAL_BROKER_SSL_ENABLED
          value: "false"
        - name: BRIDGE_ONE_WAY
          value: "true" 
      volumes:
      - name: {{ include "factorycube-unified.fullname" . }}-mqttbridge-data
        persistentVolumeClaim:
          claimName: {{ include "factorycube-unified.fullname" . }}-mqttbridge-claim
      - name: {{ include "factorycube-unified.fullname" . }}-mqttbridge-config
        configMap:
          name: {{ include "factorycube-unified.fullname" . }}-mqttbridge-config
      - name: {{ include "factorycube-unified.fullname" . }}-mqttbridge-certificates
        secret:
          secretName: {{ include "factorycube-unified.fullname" . }}-mqttbridge-secrets
{{- end }}
