{{- if or .Values.nodered.enabled .Values._000_commonConfig.dataprocessing.nodered.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:  
  name: {{ include "factorycube-unified.fullname" . }}-nodered-flows
data:  
  nodered-flows: {{ .Values.nodered.flows | toPrettyJson }}

{{- end }}
