version: '3.7'
services:
  ### Min.io: Transforms MQTT-messages in JPEGs and puts them on the Min.io blob storage with the timestamp as name
  mqtt-to-blob:
    container_name: mqtt-to-blob
    #image: minio/minio
    network_mode: host     #only for test purposes
    build:
      context: ../../
      dockerfile: ./deployment/mqtt-to-blob/Dockerfile
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    environment:
      - BROKER_URL=127.0.0.1
      - BROKER_PORT=1883
      - MINIO_URL=play.min.io
      - MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
      - MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      - TOPIC=ia/productImage/#
      - BUCKET_NAME=umhtest
      - IMAGE_UID=imageUID
      - IMAGE=image
      - IMAGE_BYTES=image_bytes
#    deploy:
#      restart_policy:
#        condition: on-failure

