version: "3"
services:

    mqtt-to-postgresql:
      container_name: mqtt-to-postgresql
      build:
        dockerfile: ./deployment/mqtt-to-postgresql/Dockerfile
        context: ../../
      environment:
        CERTIFICATE_NAME: ${CERTIFICATE_NAME}
        BROKER_URL: ${BROKER_URL}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_DATABASE: ${POSTGRES_DATABASE}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        DRY_RUN: ${DRY_RUN}
        CUSTOM_MQTT_TOPIC: ${CUSTOM_MQTT_TOPIC}
      logging:
          driver: "json-file"
          options: 
              max-file: "5"
              max-size: "10m"
      restart: unless-stopped
      volumes:
        - ../../golang/test/mqtt-to-postgresql/config/certificates:/SSL_certs
