# Copyright 2025 UMH Systems GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

agent:
  metricsPort: 8080

internal:
  redpanda:
    desiredState: stopped
    redpandaServiceConfig:
      # Note: Any change in here, will result in a restart of the Redpanda service
      topic:
        # Note: The below settings only apply to newly created topics
        # this corresponds to log_retention_ms (See also: https://docs.redpanda.com/current/manage/cluster-maintenance/disk-utilization/)
        defaultTopicRetentionMs: 604800000

        # this corresponds to retention_bytes (See also: https://docs.redpanda.com/current/manage/cluster-maintenance/disk-utilization/)
        defaultTopicRetentionBytes: 0

      resources:
        # this corresponds to --smp from scylladb/seastar
        # See also:
        # - https://docs.redpanda.com/current/manage/kubernetes/k-manage-resources/#cpu
        # By default Redpanda will use 1 core per 1000 partitions
        maxCores: 1

        # this corresponds to --memory from scylladb/seastar
        # See also:
        # - https://docs.redpanda.com/current/manage/kubernetes/k-manage-resources/#memory
        # By default Redpanda will use 4MB per partition, resulting in a theoretical maximum of 500 usable partitions per core
        # Setting this to lower then 2GB leads to startup issues!
        memoryPerCoreInBytes: 2147483648 # 2GB
