---
{{if or .Values.grafanaproxy.enabled .Values._000_commonConfig.datainput.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "united-manufacturing-hub.fullname" .}}-grafanaproxy
  labels:
    {{- include "united-manufacturing-hub.labels.grafanaproxy" . | nindent 4}}
  {{if .Values.grafanaproxy.annotations}}
  annotations:
    {{- toYaml .Values.grafanaproxy.annotations | nindent 4}}
  {{end}}
spec:
  replicas: {{.Values.grafanaproxy.replicas}}
  selector:
    matchLabels:
     {{- include "united-manufacturing-hub.labels.grafanaproxy" . | nindent 6}}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: {{include "united-manufacturing-hub.fullname" .}}-grafanaproxy
      labels:
        {{- include "united-manufacturing-hub.labels.grafanaproxy" . | nindent 8}}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    name: {{include "united-manufacturing-hub.fullname" .}}-grafanaproxy
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{include "united-manufacturing-hub.fullname" .}}-grafanaproxy
          {{if .Values.grafanaproxy.image.tag}}
          image: {{.Values.grafanaproxy.image.repository}}:{{.Values.grafanaproxy.image.tag}}
          {{- else}}
          image: {{.Values.grafanaproxy.image.repository}}:{{.Chart.AppVersion}}
          {{end}}
          imagePullPolicy: {{.Values.grafanaproxy.image.pullPolicy}}
          ports:
              - name: http
                containerPort: 80
                protocol: TCP
          resources:
            limits:
              cpu: {{.Values.grafanaproxy.resources.limits.cpu}}
            requests:
              cpu: {{.Values.grafanaproxy.resources.requests.cpu}}
          env:
            - name: FACTORYINPUT_KEY
              valueFrom:
                secretKeyRef:
                  name: factoryinput-secret
                  key: password

            - name: FACTORYINPUT_USER
              valueFrom:
                secretKeyRef:
                  name: factoryinput-secret
                  key: customerID

            - name: FACTORYINPUT_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: factoryinput-secret
                  key: baseURL

            - name: FACTORYINSIGHT_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: factoryinsight-secret
                  key: baseURL

            - name: VERSION
              value: "1"

          # define a liveness probe that checks every 1 seconds, starting after 30 seconds
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 1

          # define a readiness probe that checks every 15 seconds
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 1

      restartPolicy: Always
      terminationGracePeriodSeconds: 300 # the longest requests can up to 4 minutes
{{end}}
